version: '3.1'

services:
  gelda:
    build: .
    x-develop:
      watch:
        - action: sync
          path: .
          target: /app
    container_name: gelda
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/app
